const modelList = {
    Renault: [
        {
            name: "Duster",
            price: "430000",
        },
        {
            name: "Logan",
            price: "100000",
        },
        {
            name: "Sandero",
            price: "270000",
        },
        // "Logan Stepway седан",
        // "Logan седан",
        // "Sandero хэтчбек",
        // "Arkana кроссовер",
        // "Kaptur кроссовер",
        // "Duster кроссовер",
        // "Sandero Stepway кроссовер",
        // "Master фургон",
        // "19",
        // "Avantime",
        // "Clio",
        // "Clio RS",
        // "Dokker",
        // "Dokker Stepway",
        // "Duster",
        // "Espace",
        // "Fluence",
        // "Grand Scenic",
        // "Kangoo",
        // "Kangoo Z.E.",
        // "Kaptur",
        // "Koleos",
        // "Laguna",
        // "Latitude",
        // "Logan",
        // "Master",
        // "Megane",
        // "Megane RS",
        // "Modus",
        // "Safrane",
        // "Sandero",
        // "Sandero Stepway",
        // "Scenic",
        // "Sport Spider",
        // "Symbol",
        // "Trafic",
        // "Twingo",
        // "TWIZY",
        // "Vel Satis",
    ],
    Opel: [
        {
            name: "Astra",
            price: "100000",
        },
        {
            name: "Corsa",
            price: "190000",
        },
        {
            name: "Insignia",
            price: "360000",
        },
        // "Grandland X кроссовер",
        // "Crossland кроссовер",
        // "Zafira Life минивэн",
        // "Vivaro минивэн",
        // "Adam",
        // "Adam Rocks",
        // "Agila",
        // "Antara",
        // "Arena",
        // "Astra",
        // "Astra Family",
        // "Astra OPC",
        // "Calibra",
        // "Campo",
        // "Cascada",
        // "Combo",
        // "Corsa",
        // "Corsa OPC",
        // "Frontera",
        // "GT",
        // "Insignia",
        // "Insignia Country Tourer",
        // "Insignia OPC",
        // "Karl",
        // "Meriva",
        // "Mokka",
        // "Monterey",
        // "Movano",
        // "Omega",
        // "Signum",
        // "Sintra",
        // "Speedster",
        // "Tigra",
        // "Vectra",
        // "Vivaro",
        // "Zafira",
        // "Zafira OPC",
    ],
    Mazda: [
        {
            name: "6",
            price: "2500000",
        },
        {
            name: "CX-5",
            price: "800000",
        },
        {
            name: "Levante",
            price: "320000",
        },
        // "6 седан",
        // "CX-30 кроссовер",
        // "CX-5 кроссовер",
        // "CX-9 кроссовер",
        // "CX-9 кроссовер",
        // "121",
        // "2",
        // "3",
        // "3 MPS",
        // "323",
        // "5",
        // "6",
        // "6 MPS",
        // "626",
        // "929",
        // "Atenza",
        // "AZ-1",
        // "AZ-offroad",
        // "AZ-wagon",
        // "B-series",
        // "Bongo",
        // "BT-50",
        // "Capella",
        // "Carol",
        // "Clef",
        // "Cronos",
        // "CX-3",
        // "CX-5",
        // "CX-7",
        // "CX-9",
        // "Demio",
        // "E",
        // "Eunos 500",
        // "Eunos 800",
        // "Eunos Cosmo",
        // "Familia",
        // "Lantis",
        // "Laputa",
        // "Levante",
        // "Millenia",
        // "MPV",
        // "MX-3",
        // "MX-5",
        // "MX-6",
        // "Navajo",
        // "Premacy",
        // "Revue",
        // "Rustler",
        // "RX-7",
        // "RX-8",
        // "Scrum",
        // "Sentia",
        // "Spiano",
        // "Tribute",
        // "Vantrend",
        // "Xedos 6",
        // "Xedos 9",
    ],
    Jaguar: [
        {
            name: "E-Pace",
            price: "4100000",
        },
        {
            name: "I-Pace",
            price: "8000000",
        },
        {
            name: "F-Pace",
            price: "1890000",
        },
        // "F-Type купе",
        // "XE седан",
        // "XF седан",
        // "XJ седан",
        // "E-Pace",
        // "I-Pace",
        // "F-Pace",
        // "F-Type",
        // "F-Type SVR",
        // "S",
        // "X-Type",
        // "XE",
        // "XF",
        // "XFR",
        // "XFR-S",
        // "XJ",
        // "XJ8",
        // "XJR",
        // "XK",
        // "XK8",
        // "XKR",
        // "XKR-S",
    ],
};
export { modelList };
